var Courses = [
    {
        'name': 'Data Science With Python',
        'price': 120,
        'totalVideos' : 55,
        'totalQuizzes' : 90,
        'totalStudents' : 1500000,
        'courseRating' : 4.8,
        'courseType' : 'New',
        'courseId' : 1,
        'courseImage' : 'https://i.ibb.co/yXmfQX6/data-science-with-python-training-course-15.jpg',
        'instructorName': 'Shahed Khan Repon',
        'instructorExpert': 'AI',
        'instructorRating': '4.7',
        'instructorStudents' : 1200000,
        'instructorImage' : 'https://i.ibb.co/x6tb0FM/shahed.jpg'
    },
    
    {
        'name': 'Web Development',
        'price': 90,
        'totalVideos' : 45,
        'totalQuizzes' : 94,
        'totalStudents' : 500000,
        'courseRating' : 4.4,
        'courseType' : 'Top Rated',
        'courseId' : 2,
        'courseImage' : 'https://i.ibb.co/3dbDXxV/web-development.jpg',
        'instructorName': 'Arif Ahmed',
        'instructorExpert': 'Web Developer',
        'instructorRating': '4.9',
        'instructorStudents' : 100000,
        'instructorImage' : 'https://i.ibb.co/VQqpDnR/arif.jpg '
    },

    {
        'name': 'Web Design',
        'price': 80,
        'totalVideos' : 25,
        'totalQuizzes' : 60,
        'totalStudents' : 900000,
        'courseRating' : 4.6,
        'courseType' : 'New & Hot',
        'courseId' : 3,
        'courseImage' : 'https://i.ibb.co/2SZs2gT/web-design.jpg',
        'instructorName': 'Touhiduzzaman Tuhin',
        'instructorExpert': 'Web Designer',
        'instructorRating': '4.3',
        'instructorStudents' : 1900000,
        'instructorImage' : 'https://i.ibb.co/HFy7mgn/tuhin.jpg',
    },

    {
        'name': 'HTML Fundamentals',
        'price': 40,
        'totalVideos' : 32,
        'totalQuizzes' : 65,
        'totalStudents' : 300000,
        'courseRating' : 4.4,
        'courseType' : 'New',
        'courseId' : 4,
        'courseImage' : 'https://i.ibb.co/yNJqxG0/html-fundamentals-cover.jpg',
        'instructorName': 'Shawon Ahmed',
        'instructorExpert': 'Web Developer',
        'instructorRating': '4.7',
        'instructorStudents' : 1200000,
        'instructorImage' : 'https://i.ibb.co/k1VL1y0/shawon.jpg'
    },

    {
        'name': 'CSS Fundamentals',
        'price': 29,
        'totalVideos' : 23,
        'totalQuizzes' : 65,
        'totalStudents' : 1900000,
        'courseRating' : 4.1,
        'courseType' : 'Best Seller',
        'courseId' : 5,
        'courseImage' : 'https://i.ibb.co/4sVLq9H/css-img.png',
        'instructorName': 'Hasan Shanto',
        'instructorExpert': 'Web Developer',
        'instructorRating': '4.9',
        'instructorStudents' : 2200000,
        'instructorImage' : 'https://i.ibb.co/f4gg9Zm/shanto.jpg'
    },

    {
        'name': 'Python Fundamentals',
        'price': 50,
        'totalVideos' : 29,
        'totalQuizzes' : 76,
        'totalStudents' : 10000,
        'courseRating' : 4.5,
        'courseType' : 'New',
        'courseId' : 6,
        'courseImage' : 'https://i.ibb.co/7R79g2W/Python-Intro-MP4-Full-HD-mp4-snapshot-00-20-000.jpg',
        'instructorName': 'Sudip Sarkar',
        'instructorExpert': 'AI',
        'instructorRating': '4.7',
        'instructorStudents' : 100000,
        'instructorImage' : 'https://i.ibb.co/qn6M7S0/sudip.jpg'
    },

    {
        'name': 'Java Fundamentals',
        'price': 90,
        'totalVideos' : 90,
        'totalQuizzes' : 120,
        'totalStudents' : 4500000,
        'courseRating' : 4.5,
        'courseType' : 'New & Hot',
        'courseId' : 7,
        'courseImage' : 'https://i.ibb.co/ZdqBgH1/java.png',
        'instructorName': 'Sakila Shoha',
        'instructorExpert': 'Software Developer',
        'instructorRating': '4.2',
        'instructorStudents' : 1500000,
        'instructorImage' : 'https://i.ibb.co/x84ptMw/shoha.jpg'
    },

    {
        'name': 'JS Fundamentals',
        'price': 25,
        'totalVideos' : 44,
        'totalQuizzes' : 65,
        'totalStudents' : 190000,
        'courseRating' : 4.8,
        'courseType' : 'New',
        'courseId' : 8,
        'courseImage' : 'https://i.ibb.co/NFthYXq/Java-Script-Fundamentals-Header.jpg',
        'instructorName': 'Al Imran',
        'instructorExpert': 'Web Developer',
        'instructorRating': '4.5',
        'instructorStudents' : 1204400,
        'instructorImage' : 'https://i.ibb.co/0Kz18mn/imran.jpg'
    },

    {
        'name': 'PHP Fundamentals',
        'price': 21,
        'totalVideos' : 41,
        'totalQuizzes' : 70,
        'totalStudents' : 900000,
        'courseRating' : 4.3,
        'courseType' : 'New',
        'courseId' : 9,
        'courseImage' : 'https://i.ibb.co/DRz3TPx/php.jpg',
        'instructorName': 'Asif Mustafiz',
        'instructorExpert': 'Freelancer',
        'instructorRating': '4.5',
        'instructorStudents' : 500000,
        'instructorImage' : 'https://i.ibb.co/yQ7wnf1/asif.jpg'
    },

    {
        'name': 'Ruby Fundamentals',
        'price': 28,
        'totalVideos' : 55,
        'totalQuizzes' : 80,
        'totalStudents' : 1500000,
        'courseRating' : 4.7,
        'courseType' : 'New & Hot',
        'courseId' : 10,
        'courseImage' : 'https://i.ibb.co/cbTGdR9/ruby.jpg',
        'instructorName': 'Ali Zahan Pranto',
        'instructorExpert': 'University Teacher',
        'instructorRating': '4.3',
        'instructorStudents' : 9600000,
        'instructorImage' : 'https://i.ibb.co/FHr8Rjt/pranto.jpg'
    },

    {
        'name': 'MongoDB',
        'price': 15,
        'totalVideos' : 35,
        'totalQuizzes' : 80,
        'totalStudents' : 110000,
        'courseRating' : 4.1,
        'courseType' : 'Best Seller',
        'courseId' : 11,
        'courseImage' : 'https://i.ibb.co/kDqRBBm/mongodb.png',
        'instructorName': 'Al Mehedi Hasan',
        'instructorExpert': 'Freelancer',
        'instructorRating': '4.5',
        'instructorStudents' : 7200000,
        'instructorImage' : 'https://i.ibb.co/02pr21T/mehedi.jpg'
    },

    {
        'name': 'FullStack Web',
        'price': 150,
        'totalVideos' : 21,
        'totalQuizzes' : 43,
        'totalStudents' : 1000000,
        'courseRating' : 4.0,
        'courseType' : 'Highest Rated',
        'courseId' : 12,
        'courseImage' : 'https://i.ibb.co/fHdVXbq/full-stack.png',
        'instructorName': 'Abu Sayed',
        'instructorExpert': 'Web Developer',
        'instructorRating': '4.9',
        'instructorStudents' : 12000,
        'instructorImage' : 'https://i.ibb.co/56g28th/sayed.jpg'
    },

    {
        'name': 'FontEnd Web',
        'price': 220,
        'totalVideos' : 120,
        'totalQuizzes' : 200,
        'totalStudents' : 4500000,
        'courseRating' : 4.3,
        'courseType' : 'New',
        'courseId' : 13,
        'courseImage' : 'https://i.ibb.co/3YVXBKb/font-end.jpg',
        'instructorName': 'Pruthula',
        'instructorExpert': 'Web Developer',
        'instructorRating': '4.2',
        'instructorStudents' : 52000,
        'instructorImage' : 'https://i.ibb.co/02xBM9Z/prithula.jpg'
    },

    {
        'name': 'BackEnd Web',
        'price': 110,
        'totalVideos' : 111,
        'totalQuizzes' : 100,
        'totalStudents' : 1000000,
        'courseRating' : 4.5,
        'courseType' : 'New & Hot',
        'courseId' : 14,
        'courseImage' : 'https://i.ibb.co/7WMJtzk/back-end.png',
        'instructorName': 'Anik Ahmed',
        'instructorExpert': 'Freelancer',
        'instructorRating': '4.1',
        'instructorStudents' : 5200,
        'instructorImage' : 'https://i.ibb.co/mv5HzxL/anik.jpg'
    },

    {
        'name': 'Node Fundamentals',
        'price': 12,
        'totalVideos' : 44,
        'totalQuizzes' : 77,
        'totalStudents' : 170000,
        'courseRating' : 4.2,
        'courseType' : 'New',
        'courseId' : 15,
        'courseImage' : 'https://i.ibb.co/bQ0szBc/node.png',
        'instructorName': 'Ratul Ahmed',
        'instructorExpert': 'Web Developer',
        'instructorRating': '4.3',
        'instructorStudents' : 120000,
        'instructorImage' : 'https://i.ibb.co/9YdDMjn/ratul.jpg'
    }
];

export default Courses;